config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources "instructors"

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def create
    # 1) get values from params
    # 2) create new instructor from params that got from 1)
    # 3) If create successful, --> redirect to home page
    name = params["instructor"]["name"]
    level = params["instructor"]["level"]
    price = params["instructor"]["price"]
    role = params["instructor"]["role"]

    instructor = Instructor.new(name: name, level: level, price: price, role: role)
    if instructor.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
# Instructor = Struct.new(:name, :level, :price, :role)

class PagesController < ApplicationController
  def home
    # dummy data
    # @instructors = [
    #   Instructor.new("woot", 20, 9999, "manager"),
    #   Instructor.new("mild", 1, 1000, "teacher"),
    #   Instructor.new("toy", 1, 1000, "assistant")
    # ]

    @instructors = Instructor.all
    # Active Record

    @score = 50
    @color_score = case @score
    when 0..40
      "fail"
    when 41..50
      "need-improve"
    when 51..70
      "fair"
    when 71..100
      "excellent"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/instructors/new.html.erb
<div id="instructor-form">
  <h2>Create New Instructor</h2>
  <form action="/instructors" method="POST">
    <div class="field">
      <label for="name">Name</label>
      <input type="text" id="name" name="instructor[name]" />
    </div>
    <div class="field">
      <label for="level">Level</label>
      <input type="text" id="level" name="instructor[level]" />
    </div>
    <div class="field">
      <label for="price">Price</label>
      <input type="text" id="price" name="instructor[price]" />
    </div>
    <div class="field">
      <label for="role">Role</label>
      <input type="text" id="role" name="instructor[role]" />
    </div>
    <div class="field">
      <input type="submit" value="Create" />
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>H3f - xxxx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello H3F</h1>

<p>Ipsum sit illo adipisci accusantium sit? Minima nesciunt facere est repudiandae unde. Dicta quaerat nihil modi ut sint! Ratione nemo vitae animi ipsa nesciunt. Officia placeat eum animi ipsam rem</p>

<div class="actions">
  <%= link_to "Create Instructor", new_instructor_path %>
  <!-- <a href="/instructors/new">Create Instructor</a> -->
</div>

<div>
  <h2>List of instructors</h2>
  <div class="instructors">
    <div class="instructor header">
      <div>Name</div>
      <div>Level</div>
      <div>Price</div>
    </div>
    <% @instructors.each do |ins| %>
      <div class="instructor">
        <div class="instructor-name"><%= ins.name %></div>
        <div class="instructor-level"><%= ins.level %></div>
        <div class="instructor-price"><%= ins.price %></div>
      </div>
    <% end %>
  </div>
</div>

<div class="result" data-score="<%= @score %>">
  <div class="score <%= @color_score %>"><%= @score %></div>
</div>